kh-semiProject-semiColon/semiProject

SemiProject/src/main/java/kr/co/semi/main/controller/MainController.java, SemiProject/src/main/resources/static/css/common/footer.css, SemiProject/src/main/resources/static/css/common/header.css, SemiProject/src/main/resources/static/css/signup.css, SemiProject/src/main/resources/static/css/study/study-creation.css, SemiProject/src/main/resources/templates/common/main.html, SemiProject/src/main/resources/templates/study/study-creation.html
main.css에 헤더와 풋터 css 가 함께 들어가 있었는데 조각으로 분리하여 css를 따로 뺌
=> 헤더 푸터main.css 와 분리

SemiProject/src/main/java/kr/co/semi/main/Mapper/MainMapper.java, SemiProject/src/main/java/kr/co/semi/main/controller/MainController.java, SemiProject/src/main/java/kr/co/semi/main/service/MainServiceImpl.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/dto/Study.java, SemiProject/src/main/resources/mappers/study-mapper.xml, SemiProject/src/main/resources/static/js/study/study-creation.js, SemiProject/src/main/resources/templates/study/study-creation.html
=> 스터디 생성기능 추가

SemiProject/src/main/java/kr/co/semi/main/Mapper/MainMapper.java, SemiProject/src/main/java/kr/co/semi/main/controller/MainController.java, SemiProject/src/main/java/kr/co/semi/main/service/MainService.java, SemiProject/src/main/java/kr/co/semi/main/service/MainServiceImpl.java, SemiProject/src/main/resources/mappers/study-mapper.xml, SemiProject/src/main/resources/static/css/study/study-creation.css, SemiProject/src/main/resources/static/js/study/study-creation.js, SemiProject/src/main/resources/static/popup/Excel.html, SemiProject/src/main/resources/templates/common/main.html, SemiProject/src/main/resources/templates/study/study-creation.html
스터디 생성 시 스터디명 유효성 검사와 더불어 중복검사
=> 스터디명 중복검사 완료

SemiProject/src/main/java/kr/co/semi/studyboard/controller/StudyController.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/dto/Study.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/mapper/StudyMapper.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/service/StudyService.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/service/StudyServiceImpl.java, SemiProject/src/main/resources/mappers/study-info-mapper.xml, SemiProject/src/main/resources/templates/study/studyNow.html
=> 스터디 인원수 조회 코드 효율적으로 수정

SemiProject/src/main/resources/static/js/study/studyslider.js, SemiProject/src/main/resources/templates/common/main.html
미니 스터디 현황 슬라이더 일정시간 지나면 넘어가기 기능 추가
=> 미니 스터디현황 슬라이더 일정시간지나면 자동 넘기기 기능

SemiProject/src/main/resources/static/js/studyCal.js
=> 스터디 전용 캘린더 색상수정 버튼 변경

SemiProject/src/main/java/kr/co/semi/studyboard/controller/StudyBoardController.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/dto/Study.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/dto/StudyBoard.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/dto/StudyComment.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/mapper/StudyBoardMapper.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/service/StudyBoardService.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/service/StudyBoardServiceImpl.java, SemiProject/src/main/resources/mappers/studyboard-mapper.xml, SemiProject/src/main/resources/static/js/studyBoard/update.js, SemiProject/src/main/resources/templates/studyboard/rulecontent.html, SemiProject/src/main/resources/templates/studyboard/studyboard.html, SemiProject/src/main/resources/templates/studyboard/update.html
내규 완료
스터디 정보수정 - 수정 부분 (출력부분 완료) 오류 수정 전 
스터디 테이블 html 수청 필요!
회원 탈퇴 아직 미완료
=> 내규 정보까지 완료

SemiProject/src/main/java/kr/co/semi/studyboard/controller/StudyBoardController.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/mapper/StudyBoardMapper.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/service/StudyBoardService.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/service/StudyBoardServiceImpl.java, SemiProject/src/main/resources/mappers/studyboard-mapper.xml, SemiProject/src/main/resources/static/js/cal.js, SemiProject/src/main/resources/static/js/studyCal.js, SemiProject/src/main/resources/templates/common/main.html, SemiProject/src/main/resources/templates/studyboard/calendar.html, SemiProject/src/main/resources/templates/studyboard/studyboard.html
=> 스터디 게시판 조회

SemiProject/src/main/java/kr/co/semi/studyboard/controller/StudyBoardController.java, SemiProject/src/main/resources/static/css/studyBoard/delete.css, SemiProject/src/main/resources/static/css/studyBoard/update.css, SemiProject/src/main/resources/templates/studyboard/delete.html, SemiProject/src/main/resources/templates/studyboard/sidebar.html, SemiProject/src/main/resources/templates/studyboard/update.html
=> 스터디게시판 백그라운드까지

SemiProject/src/main/java/kr/co/semi/myPage/controller/MyPageController.java, SemiProject/src/main/java/kr/co/semi/myPage/model/service/MyPageService.java, SemiProject/src/main/java/kr/co/semi/myPage/model/service/MyPageServiceImpl.java, SemiProject/src/main/resources/static/js/myPage/myPage-info.js, SemiProject/src/main/resources/templates/myPage/myPage-info.html
아침부터 실례드립니다
인포부분 js, html, 컨트롤러 서비스 서비스 임풀 변경본 첨부 드립니다
=> 프로필 사진 조회 진행

SemiProject/src/main/java/kr/co/semi/board/controller/BoardController.java, SemiProject/src/main/java/kr/co/semi/board/controller/EditBoardController.java, SemiProject/src/main/java/kr/co/semi/board/model/mapper/EditBoardMapper.java, SemiProject/src/main/java/kr/co/semi/board/model/service/BoardService.java, SemiProject/src/main/java/kr/co/semi/board/model/service/EditBoardService.java, SemiProject/src/main/java/kr/co/semi/board/model/service/EditBoardServiceImpl.java, SemiProject/src/main/java/kr/co/semi/member/controller/MemberController.java, SemiProject/src/main/resources/mappers/board-mapper.xml, SemiProject/src/main/resources/mappers/editBoard-mapper.xml, SemiProject/src/main/resources/static/css/board/boardDetail.css, SemiProject/src/main/resources/static/js/board/announce.js, SemiProject/src/main/resources/templates/board/announce.html, SemiProject/src/main/resources/templates/board/announceDetail.html, SemiProject/src/main/resources/templates/board/announceUpdate.html, SemiProject/src/main/resources/templates/board/announceWrite.html, SemiProject/src/main/resources/templates/board/boardDetail.html
공지사항 글쓰기 관리자만 가능. 본인 글 수정 삭제 본인만 가능
해야할 일 : css
=> 조건에 따른 글쓰기 수정 삭제 버튼

SemiProject/src/main/resources/templates/common/header.html, SemiProject/src/main/resources/templates/common/main.html
=> 로그인 후 스터디 게시판 제한사항 추가

SemiProject/src/main/java/kr/co/semi/common/exception/ExceptionController.java, SemiProject/src/main/java/kr/co/semi/studyboard/controller/StudyBoardController.java, SemiProject/src/main/resources/templates/error/404.html, SemiProject/src/main/resources/templates/error/500.html
=> 404,500 에러페이지 추가

SemiProject/src/main/java/kr/co/semi/member/controller/MemberController.java, SemiProject/src/main/java/kr/co/semi/member/model/service/MemberSerivceImpl.java
프로필 경로가 webpath가 아닌 folderpath로 되어있었습니다.
=> 프로필 경로 지정 이슈

SemiProject/src/main/resources/templates/common/main.html
=> 한명이 한개의 스터디만 생성가능

SemiProject/src/main/java/kr/co/semi/studyboard/controller/StudyBoardController.java, SemiProject/src/main/java/kr/co/semi/studyboard/controller/StudyCommentController.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/dto/StudyComment.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/mapper/StudyCommentMapper.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/service/StudyCommentService.java, SemiProject/src/main/java/kr/co/semi/studyboard/model/service/StudyCommentServiceImpl.java, SemiProject/src/main/resources/mappers/study-comment-mapper.xml, SemiProject/src/main/resources/mappers/studyboard-mapper.xml, SemiProject/src/main/resources/static/js/studyBoard/studyComment.js, SemiProject/src/main/resources/templates/studyboard/studyBoardDetail.html, SemiProject/src/main/resources/templates/studyboard/studyComment.html
=> 스터디 게시판 댓글 완료

SemiProject/src/main/java/kr/co/semi/board/model/dto/HireInfo.java, SemiProject/src/main/java/kr/co/semi/main/Mapper/MainMapper.java, SemiProject/src/main/java/kr/co/semi/main/controller/MainController.java, SemiProject/src/main/java/kr/co/semi/main/service/MainService.java, SemiProject/src/main/java/kr/co/semi/main/service/MainServiceImpl.java, SemiProject/src/main/resources/mappers/study-mapper.xml, SemiProject/src/main/resources/static/css/main.css, SemiProject/src/main/resources/templates/common/main.html
=> 최신 공지사항 불러오기 및 최신 구인게시글 불러오기

SemiProject/src/main/java/kr/co/semi/studyboard/controller/StudyBoardController.java, SemiProject/src/main/resources/templates/studyboard/delete.html
=> 스터디 해체 기능 수정

SemiProject/src/main/resources/templates/common/header.html, SemiProject/src/main/resources/templates/common/main.html, SemiProject/src/main/resources/templates/studyboard/update.html
가입된 스터디 없어도 메인페이지가 아닌 다른 페이지에 있을 경우 헤더를 통해 스터디 게시판 이동 가능.
header에 script 추가해서 막음
=> header 스터디 막기

SemiProject/src/main/resources/templates/studyboard/realtime_study_chat.html, SemiProject/src/main/resources/templates/studyboard/study_chat_room.html
=> 스터디 채팅 오류 수정

SemiProject/src/main/resources/static/css/hire/hireComment.css, SemiProject/src/main/resources/templates/hire/hireDetail.html
=> 조회수 위치 수정 , 답글수정삭제 호버 효과 수정

SemiProject/src/main/java/kr/co/semi/common/config/InterceptorConfig.java, SemiProject/src/main/java/kr/co/semi/common/interceptor/LoginInterceptor.java, SemiProject/src/main/java/kr/co/semi/common/interceptor/SessionUpdateInterceptor.java, SemiProject/src/main/java/kr/co/semi/common/interceptor/model/mapper/UserSessionUpdateMapper.java, SemiProject/src/main/java/kr/co/semi/common/interceptor/model/service/UserSessionUpdate.java, SemiProject/src/main/java/kr/co/semi/common/interceptor/model/service/UserSessionUpdateImpl.java, SemiProject/src/main/java/kr/co/semi/studyboard/controller/StudyBoardController.java, SemiProject/src/main/resources/mappers/sessionUpdate-mapper.xml
=> 스터디관련 인터셉터
